services:
  db:
    image: postgres:16
    container_name: transaction_db
    environment:
      POSTGRES_USER: transaction_user
      POSTGRES_PASSWORD: 123456***
      POSTGRES_DB: transaction_manager
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: transaction_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://transaction_user:123456***@db:5432/transaction_manager
    ports:
      - "5001:5001"
    volumes:
      - .:/app

volumes:
  db_data: